from pydantic import BaseModel

SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_ERROR = "error"
SEVERITY_CRITICAL = "critical"

# Códigos padronizados do contrato de warnings/errors.
QA_NO_ARTIFACTS = "QA_NO_ARTIFACTS"
QA_FALLBACK_MOCK = "QA_FALLBACK_MOCK"
PROJECT_TASK_NOT_ALLOWED = "PROJECT_TASK_NOT_ALLOWED"
PROJECT_POLICY_NOT_ENFORCED = "PROJECT_POLICY_NOT_ENFORCED"
UNKNOWN_ORIGIN_SYSTEM = "UNKNOWN_ORIGIN_SYSTEM"
UNKNOWN_TASK_TYPE = "UNKNOWN_TASK_TYPE"
ARTIFACT_VISUAL_UNSUPPORTED = "ARTIFACT_VISUAL_UNSUPPORTED"
ARTIFACT_TRUNCATED = "ARTIFACT_TRUNCATED"
ARTIFACT_PATH_REJECTED = "ARTIFACT_PATH_REJECTED"
ARTIFACT_EMPTY_CONTENT = "ARTIFACT_EMPTY_CONTENT"
ARTIFACT_TYPE_UNKNOWN = "ARTIFACT_TYPE_UNKNOWN"
QA_ARTIFACT_LIMIT_EXCEEDED = "QA_ARTIFACT_LIMIT_EXCEEDED"
PROVIDER_REAL_BLOCKED = "PROVIDER_REAL_BLOCKED"
INTERNAL_AUTH_NOT_CONFIGURED = "INTERNAL_AUTH_NOT_CONFIGURED"
INTERNAL_AUTH_INVALID = "INTERNAL_AUTH_INVALID"
INTERNAL_AUTH_MISSING = "INTERNAL_AUTH_MISSING"
RELEASE_GATE_BLOCKED = "RELEASE_GATE_BLOCKED"
QA_RISK_CRITICAL = "QA_RISK_CRITICAL"
QA_FAILURE_DETECTED = "QA_FAILURE_DETECTED"
QA_ERROR_DETECTED = "QA_ERROR_DETECTED"
QA_WARNING_DETECTED = "QA_WARNING_DETECTED"
QA_LOCAL_HEURISTIC = "QA_LOCAL_HEURISTIC"

_SEVERITIES: dict[str, str] = {
    QA_NO_ARTIFACTS: SEVERITY_WARNING,
    QA_FALLBACK_MOCK: SEVERITY_WARNING,
    PROJECT_TASK_NOT_ALLOWED: SEVERITY_WARNING,
    PROJECT_POLICY_NOT_ENFORCED: SEVERITY_INFO,
    UNKNOWN_ORIGIN_SYSTEM: SEVERITY_WARNING,
    UNKNOWN_TASK_TYPE: SEVERITY_WARNING,
    ARTIFACT_VISUAL_UNSUPPORTED: SEVERITY_WARNING,
    ARTIFACT_TRUNCATED: SEVERITY_WARNING,
    ARTIFACT_PATH_REJECTED: SEVERITY_ERROR,
    ARTIFACT_EMPTY_CONTENT: SEVERITY_WARNING,
    ARTIFACT_TYPE_UNKNOWN: SEVERITY_WARNING,
    QA_ARTIFACT_LIMIT_EXCEEDED: SEVERITY_WARNING,
    PROVIDER_REAL_BLOCKED: SEVERITY_WARNING,
    INTERNAL_AUTH_NOT_CONFIGURED: SEVERITY_WARNING,
    INTERNAL_AUTH_INVALID: SEVERITY_ERROR,
    INTERNAL_AUTH_MISSING: SEVERITY_ERROR,
    RELEASE_GATE_BLOCKED: SEVERITY_ERROR,
    QA_RISK_CRITICAL: SEVERITY_CRITICAL,
    QA_FAILURE_DETECTED: SEVERITY_ERROR,
    QA_ERROR_DETECTED: SEVERITY_ERROR,
    QA_WARNING_DETECTED: SEVERITY_WARNING,
    QA_LOCAL_HEURISTIC: SEVERITY_INFO,
}


class WarningItem(BaseModel):
    code: str
    message: str
    severity: str = SEVERITY_WARNING


def severity_for(code: str) -> str:
    return _SEVERITIES.get(code, SEVERITY_WARNING)


def make_warning(code: str, message: str, severity: str | None = None) -> WarningItem:
    return WarningItem(code=code, message=message, severity=severity or severity_for(code))
