from pydantic import BaseModel

SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_ERROR = "error"
SEVERITY_CRITICAL = "critical"

# Códigos padronizados do contrato de warnings/errors.
QA_NO_ARTIFACTS = "QA_NO_ARTIFACTS"
QA_FALLBACK_MOCK = "QA_FALLBACK_MOCK"
PROJECT_TASK_NOT_ALLOWED = "PROJECT_TASK_NOT_ALLOWED"
PROJECT_POLICY_NOT_ENFORCED = "PROJECT_POLICY_NOT_ENFORCED"
UNKNOWN_ORIGIN_SYSTEM = "UNKNOWN_ORIGIN_SYSTEM"
UNKNOWN_TASK_TYPE = "UNKNOWN_TASK_TYPE"
ARTIFACT_VISUAL_UNSUPPORTED = "ARTIFACT_VISUAL_UNSUPPORTED"
ARTIFACT_TRUNCATED = "ARTIFACT_TRUNCATED"
ARTIFACT_PATH_REJECTED = "ARTIFACT_PATH_REJECTED"
ARTIFACT_EMPTY_CONTENT = "ARTIFACT_EMPTY_CONTENT"
ARTIFACT_TYPE_UNKNOWN = "ARTIFACT_TYPE_UNKNOWN"
QA_ARTIFACT_LIMIT_EXCEEDED = "QA_ARTIFACT_LIMIT_EXCEEDED"
PROVIDER_REAL_BLOCKED = "PROVIDER_REAL_BLOCKED"
PROVIDER_REAL_UNAVAILABLE = "PROVIDER_REAL_UNAVAILABLE"
PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
INTERNAL_AUTH_NOT_CONFIGURED = "INTERNAL_AUTH_NOT_CONFIGURED"
INTERNAL_AUTH_INVALID = "INTERNAL_AUTH_INVALID"
INTERNAL_AUTH_MISSING = "INTERNAL_AUTH_MISSING"
RELEASE_GATE_BLOCKED = "RELEASE_GATE_BLOCKED"
QA_RISK_CRITICAL = "QA_RISK_CRITICAL"
QA_FAILURE_DETECTED = "QA_FAILURE_DETECTED"
QA_ERROR_DETECTED = "QA_ERROR_DETECTED"
QA_WARNING_DETECTED = "QA_WARNING_DETECTED"
QA_LOCAL_HEURISTIC = "QA_LOCAL_HEURISTIC"

# Bloco 9 — Artifact Reader controlado por allowlist.
ARTIFACT_READER_DISABLED = "ARTIFACT_READER_DISABLED"
ARTIFACT_READER_USED = "ARTIFACT_READER_USED"
ARTIFACT_READER_PATH_NOT_ALLOWED = "ARTIFACT_READER_PATH_NOT_ALLOWED"
ARTIFACT_READER_EXTENSION_BLOCKED = "ARTIFACT_READER_EXTENSION_BLOCKED"
ARTIFACT_READER_FILE_TOO_LARGE = "ARTIFACT_READER_FILE_TOO_LARGE"
ARTIFACT_READER_TOTAL_LIMIT_EXCEEDED = "ARTIFACT_READER_TOTAL_LIMIT_EXCEEDED"
ARTIFACT_READER_ENV_BLOCKED = "ARTIFACT_READER_ENV_BLOCKED"
ARTIFACT_READER_BINARY_BLOCKED = "ARTIFACT_READER_BINARY_BLOCKED"
ARTIFACT_READER_PATH_TRAVERSAL_BLOCKED = "ARTIFACT_READER_PATH_TRAVERSAL_BLOCKED"
ARTIFACT_READER_SECRET_BLOCKED = "ARTIFACT_READER_SECRET_BLOCKED"

# Bloco 10 — QA visual stub (sem OCR, sem provider multimodal, sem Playwright).
VISUAL_QA_NOT_ENABLED = "VISUAL_QA_NOT_ENABLED"
VISUAL_QA_REQUIRES_HUMAN_REVIEW = "VISUAL_QA_REQUIRES_HUMAN_REVIEW"
VISUAL_QA_PROVIDER_NOT_CONFIGURED = "VISUAL_QA_PROVIDER_NOT_CONFIGURED"
VISUAL_QA_BLOCKED_FOR_RELEASE_GATE = "VISUAL_QA_BLOCKED_FOR_RELEASE_GATE"

# Bloco 11 — Agente exploratório assistido (plano/manual, sem execução).
EXPLORATION_ASSISTED_ONLY = "EXPLORATION_ASSISTED_ONLY"
EXPLORATION_ACTION_BLOCKED = "EXPLORATION_ACTION_BLOCKED"
HUMAN_CONFIRMATION_REQUIRED = "HUMAN_CONFIRMATION_REQUIRED"
EXPLORATION_CANNOT_EXECUTE_COMMANDS = "EXPLORATION_CANNOT_EXECUTE_COMMANDS"
EXPLORATION_CANNOT_ACCESS_SYSTEM = "EXPLORATION_CANNOT_ACCESS_SYSTEM"
EXPLORATION_RELEASE_GATE_BLOCKED = "EXPLORATION_RELEASE_GATE_BLOCKED"

# IMPLEMENT-05 — recursos reais controlados e enforcement final.
REAL_INTEGRATION_TESTS_DISABLED = "REAL_INTEGRATION_TESTS_DISABLED"
REAL_FINGUARD_TESTS_DISABLED = "REAL_FINGUARD_TESTS_DISABLED"
REAL_PROVIDER_TESTS_DISABLED = "REAL_PROVIDER_TESTS_DISABLED"
REAL_PLAYWRIGHT_TESTS_DISABLED = "REAL_PLAYWRIGHT_TESTS_DISABLED"
REAL_OCR_TESTS_DISABLED = "REAL_OCR_TESTS_DISABLED"
REAL_MULTIMODAL_TESTS_DISABLED = "REAL_MULTIMODAL_TESTS_DISABLED"
REAL_FEATURE_REQUIRES_EXPLICIT_FLAG = "REAL_FEATURE_REQUIRES_EXPLICIT_FLAG"
REAL_FEATURE_REQUIRES_HUMAN_CONFIRMATION = "REAL_FEATURE_REQUIRES_HUMAN_CONFIRMATION"
OCR_NOT_ENABLED = "OCR_NOT_ENABLED"
OCR_DEPENDENCY_UNAVAILABLE = "OCR_DEPENDENCY_UNAVAILABLE"
OCR_REQUIRES_HUMAN_REVIEW = "OCR_REQUIRES_HUMAN_REVIEW"
MULTIMODAL_PROVIDER_DISABLED = "MULTIMODAL_PROVIDER_DISABLED"
MULTIMODAL_PROVIDER_REQUIRES_EXPLICIT_AUTH = "MULTIMODAL_PROVIDER_REQUIRES_EXPLICIT_AUTH"
MULTIMODAL_PROVIDER_REQUIRES_FLAG = "MULTIMODAL_PROVIDER_REQUIRES_FLAG"
PLAYWRIGHT_NOT_ENABLED = "PLAYWRIGHT_NOT_ENABLED"
PLAYWRIGHT_DEPENDENCY_UNAVAILABLE = "PLAYWRIGHT_DEPENDENCY_UNAVAILABLE"
PLAYWRIGHT_BASE_URL_NOT_ALLOWED = "PLAYWRIGHT_BASE_URL_NOT_ALLOWED"
PLAYWRIGHT_READ_ONLY_MODE = "PLAYWRIGHT_READ_ONLY_MODE"
PLAYWRIGHT_ACTION_BLOCKED = "PLAYWRIGHT_ACTION_BLOCKED"
PLAYWRIGHT_REQUIRES_HUMAN_REVIEW = "PLAYWRIGHT_REQUIRES_HUMAN_REVIEW"
FINGUARD_REAL_INTEGRATION_DISABLED = "FINGUARD_REAL_INTEGRATION_DISABLED"
FINGUARD_REPOSITORY_ACCESS_BLOCKED = "FINGUARD_REPOSITORY_ACCESS_BLOCKED"
FINGUARD_TASK_NOT_ALLOWED = "FINGUARD_TASK_NOT_ALLOWED"
PROJECT_POLICY_ENFORCED = "PROJECT_POLICY_ENFORCED"
PROJECT_POLICY_BLOCKED = "PROJECT_POLICY_BLOCKED"
RELEASE_REQUIRES_HUMAN_REVIEW = "RELEASE_REQUIRES_HUMAN_REVIEW"
RELEASE_REAL_FEATURE_BLOCKED = "RELEASE_REAL_FEATURE_BLOCKED"

# ECOSYSTEM-INTELLIGENCE-SUITE-01 — assistente de ecossistema, memória técnica
# e provider local generativo opt-in.
FINANCIAL_DISCLAIMER = "FINANCIAL_DISCLAIMER"
REPORT_MEMORY_IS_NOT_TRAINING = "REPORT_MEMORY_IS_NOT_TRAINING"
REPORT_MEMORY_USED = "REPORT_MEMORY_USED"
REPORT_MEMORY_DISABLED = "REPORT_MEMORY_DISABLED"
REPORT_MEMORY_EMPTY = "REPORT_MEMORY_EMPTY"
LOCAL_MODEL_DISABLED = "LOCAL_MODEL_DISABLED"
LOCAL_MODEL_NOT_AUTHORIZED = "LOCAL_MODEL_NOT_AUTHORIZED"
LOCAL_MODEL_TASK_BLOCKED = "LOCAL_MODEL_TASK_BLOCKED"
LOCAL_MODEL_TRANSPORT_UNAVAILABLE = "LOCAL_MODEL_TRANSPORT_UNAVAILABLE"
LOCAL_MODEL_USED = "LOCAL_MODEL_USED"

# MULTI-PROVIDER-SAFE-EVOLUTION Etapa 2 — identidade autenticada do caller e
# autorização de provider por projeto/ambiente (fail-closed).
CALLER_CREDENTIAL_MISSING = "CALLER_CREDENTIAL_MISSING"
CALLER_CREDENTIAL_UNKNOWN = "CALLER_CREDENTIAL_UNKNOWN"
CALLER_REGISTRY_INVALID = "CALLER_REGISTRY_INVALID"
CALLER_ORIGIN_MISMATCH = "CALLER_ORIGIN_MISMATCH"
CALLER_PROVIDER_SELECTION_NOT_ALLOWED = "CALLER_PROVIDER_SELECTION_NOT_ALLOWED"
CALLER_MODEL_SELECTION_NOT_ALLOWED = "CALLER_MODEL_SELECTION_NOT_ALLOWED"
CALLER_IDENTITY_SHARED_CREDENTIAL = "CALLER_IDENTITY_SHARED_CREDENTIAL"
CALLER_IDENTITY_AMBIGUOUS = "CALLER_IDENTITY_AMBIGUOUS"
PROVIDER_NOT_AUTHORIZED_FOR_PROJECT = "PROVIDER_NOT_AUTHORIZED_FOR_PROJECT"
PROVIDER_NOT_HOMOLOGATED = "PROVIDER_NOT_HOMOLOGATED"
PROVIDER_NOT_IMPLEMENTED = "PROVIDER_NOT_IMPLEMENTED"

_SEVERITIES: dict[str, str] = {
    QA_NO_ARTIFACTS: SEVERITY_WARNING,
    QA_FALLBACK_MOCK: SEVERITY_WARNING,
    PROJECT_TASK_NOT_ALLOWED: SEVERITY_WARNING,
    PROJECT_POLICY_NOT_ENFORCED: SEVERITY_INFO,
    UNKNOWN_ORIGIN_SYSTEM: SEVERITY_WARNING,
    UNKNOWN_TASK_TYPE: SEVERITY_WARNING,
    ARTIFACT_VISUAL_UNSUPPORTED: SEVERITY_WARNING,
    ARTIFACT_TRUNCATED: SEVERITY_WARNING,
    ARTIFACT_PATH_REJECTED: SEVERITY_ERROR,
    ARTIFACT_EMPTY_CONTENT: SEVERITY_WARNING,
    ARTIFACT_TYPE_UNKNOWN: SEVERITY_WARNING,
    QA_ARTIFACT_LIMIT_EXCEEDED: SEVERITY_WARNING,
    PROVIDER_REAL_BLOCKED: SEVERITY_WARNING,
    PROVIDER_REAL_UNAVAILABLE: SEVERITY_WARNING,
    PROVIDER_TIMEOUT: SEVERITY_WARNING,
    INTERNAL_AUTH_NOT_CONFIGURED: SEVERITY_WARNING,
    INTERNAL_AUTH_INVALID: SEVERITY_ERROR,
    INTERNAL_AUTH_MISSING: SEVERITY_ERROR,
    RELEASE_GATE_BLOCKED: SEVERITY_ERROR,
    QA_RISK_CRITICAL: SEVERITY_CRITICAL,
    QA_FAILURE_DETECTED: SEVERITY_ERROR,
    QA_ERROR_DETECTED: SEVERITY_ERROR,
    QA_WARNING_DETECTED: SEVERITY_WARNING,
    QA_LOCAL_HEURISTIC: SEVERITY_INFO,
    ARTIFACT_READER_DISABLED: SEVERITY_WARNING,
    ARTIFACT_READER_USED: SEVERITY_INFO,
    ARTIFACT_READER_PATH_NOT_ALLOWED: SEVERITY_ERROR,
    ARTIFACT_READER_EXTENSION_BLOCKED: SEVERITY_ERROR,
    ARTIFACT_READER_FILE_TOO_LARGE: SEVERITY_WARNING,
    ARTIFACT_READER_TOTAL_LIMIT_EXCEEDED: SEVERITY_WARNING,
    ARTIFACT_READER_ENV_BLOCKED: SEVERITY_CRITICAL,
    ARTIFACT_READER_BINARY_BLOCKED: SEVERITY_ERROR,
    ARTIFACT_READER_PATH_TRAVERSAL_BLOCKED: SEVERITY_ERROR,
    ARTIFACT_READER_SECRET_BLOCKED: SEVERITY_CRITICAL,
    VISUAL_QA_NOT_ENABLED: SEVERITY_WARNING,
    VISUAL_QA_REQUIRES_HUMAN_REVIEW: SEVERITY_WARNING,
    VISUAL_QA_PROVIDER_NOT_CONFIGURED: SEVERITY_INFO,
    VISUAL_QA_BLOCKED_FOR_RELEASE_GATE: SEVERITY_ERROR,
    EXPLORATION_ASSISTED_ONLY: SEVERITY_INFO,
    EXPLORATION_ACTION_BLOCKED: SEVERITY_WARNING,
    HUMAN_CONFIRMATION_REQUIRED: SEVERITY_WARNING,
    EXPLORATION_CANNOT_EXECUTE_COMMANDS: SEVERITY_INFO,
    EXPLORATION_CANNOT_ACCESS_SYSTEM: SEVERITY_INFO,
    EXPLORATION_RELEASE_GATE_BLOCKED: SEVERITY_ERROR,
    REAL_INTEGRATION_TESTS_DISABLED: SEVERITY_INFO,
    REAL_FINGUARD_TESTS_DISABLED: SEVERITY_INFO,
    REAL_PROVIDER_TESTS_DISABLED: SEVERITY_INFO,
    REAL_PLAYWRIGHT_TESTS_DISABLED: SEVERITY_INFO,
    REAL_OCR_TESTS_DISABLED: SEVERITY_INFO,
    REAL_MULTIMODAL_TESTS_DISABLED: SEVERITY_INFO,
    REAL_FEATURE_REQUIRES_EXPLICIT_FLAG: SEVERITY_WARNING,
    REAL_FEATURE_REQUIRES_HUMAN_CONFIRMATION: SEVERITY_WARNING,
    OCR_NOT_ENABLED: SEVERITY_WARNING,
    OCR_DEPENDENCY_UNAVAILABLE: SEVERITY_WARNING,
    OCR_REQUIRES_HUMAN_REVIEW: SEVERITY_WARNING,
    MULTIMODAL_PROVIDER_DISABLED: SEVERITY_WARNING,
    MULTIMODAL_PROVIDER_REQUIRES_EXPLICIT_AUTH: SEVERITY_WARNING,
    MULTIMODAL_PROVIDER_REQUIRES_FLAG: SEVERITY_WARNING,
    PLAYWRIGHT_NOT_ENABLED: SEVERITY_WARNING,
    PLAYWRIGHT_DEPENDENCY_UNAVAILABLE: SEVERITY_WARNING,
    PLAYWRIGHT_BASE_URL_NOT_ALLOWED: SEVERITY_ERROR,
    PLAYWRIGHT_READ_ONLY_MODE: SEVERITY_INFO,
    PLAYWRIGHT_ACTION_BLOCKED: SEVERITY_ERROR,
    PLAYWRIGHT_REQUIRES_HUMAN_REVIEW: SEVERITY_WARNING,
    FINGUARD_REAL_INTEGRATION_DISABLED: SEVERITY_INFO,
    FINGUARD_REPOSITORY_ACCESS_BLOCKED: SEVERITY_ERROR,
    FINGUARD_TASK_NOT_ALLOWED: SEVERITY_ERROR,
    PROJECT_POLICY_ENFORCED: SEVERITY_INFO,
    PROJECT_POLICY_BLOCKED: SEVERITY_ERROR,
    RELEASE_REQUIRES_HUMAN_REVIEW: SEVERITY_ERROR,
    RELEASE_REAL_FEATURE_BLOCKED: SEVERITY_ERROR,
    FINANCIAL_DISCLAIMER: SEVERITY_INFO,
    REPORT_MEMORY_IS_NOT_TRAINING: SEVERITY_INFO,
    REPORT_MEMORY_USED: SEVERITY_INFO,
    REPORT_MEMORY_DISABLED: SEVERITY_WARNING,
    REPORT_MEMORY_EMPTY: SEVERITY_INFO,
    LOCAL_MODEL_DISABLED: SEVERITY_WARNING,
    LOCAL_MODEL_NOT_AUTHORIZED: SEVERITY_WARNING,
    LOCAL_MODEL_TASK_BLOCKED: SEVERITY_ERROR,
    LOCAL_MODEL_TRANSPORT_UNAVAILABLE: SEVERITY_WARNING,
    LOCAL_MODEL_USED: SEVERITY_INFO,
    CALLER_CREDENTIAL_MISSING: SEVERITY_ERROR,
    CALLER_CREDENTIAL_UNKNOWN: SEVERITY_ERROR,
    CALLER_REGISTRY_INVALID: SEVERITY_CRITICAL,
    CALLER_ORIGIN_MISMATCH: SEVERITY_ERROR,
    CALLER_PROVIDER_SELECTION_NOT_ALLOWED: SEVERITY_ERROR,
    CALLER_MODEL_SELECTION_NOT_ALLOWED: SEVERITY_ERROR,
    CALLER_IDENTITY_SHARED_CREDENTIAL: SEVERITY_INFO,
    CALLER_IDENTITY_AMBIGUOUS: SEVERITY_ERROR,
    PROVIDER_NOT_AUTHORIZED_FOR_PROJECT: SEVERITY_ERROR,
    PROVIDER_NOT_HOMOLOGATED: SEVERITY_WARNING,
    PROVIDER_NOT_IMPLEMENTED: SEVERITY_WARNING,
}


class WarningItem(BaseModel):
    code: str
    message: str
    severity: str = SEVERITY_WARNING


def severity_for(code: str) -> str:
    return _SEVERITIES.get(code, SEVERITY_WARNING)


def make_warning(code: str, message: str, severity: str | None = None) -> WarningItem:
    return WarningItem(code=code, message=message, severity=severity or severity_for(code))
