from pydantic import BaseModel

SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_ERROR = "error"
SEVERITY_CRITICAL = "critical"

# Códigos padronizados do contrato de warnings/errors.
QA_NO_ARTIFACTS = "QA_NO_ARTIFACTS"
QA_FALLBACK_MOCK = "QA_FALLBACK_MOCK"
PROJECT_TASK_NOT_ALLOWED = "PROJECT_TASK_NOT_ALLOWED"
PROJECT_POLICY_NOT_ENFORCED = "PROJECT_POLICY_NOT_ENFORCED"
UNKNOWN_ORIGIN_SYSTEM = "UNKNOWN_ORIGIN_SYSTEM"
UNKNOWN_TASK_TYPE = "UNKNOWN_TASK_TYPE"
ARTIFACT_VISUAL_UNSUPPORTED = "ARTIFACT_VISUAL_UNSUPPORTED"
ARTIFACT_TRUNCATED = "ARTIFACT_TRUNCATED"
ARTIFACT_PATH_REJECTED = "ARTIFACT_PATH_REJECTED"
ARTIFACT_EMPTY_CONTENT = "ARTIFACT_EMPTY_CONTENT"
ARTIFACT_TYPE_UNKNOWN = "ARTIFACT_TYPE_UNKNOWN"
QA_ARTIFACT_LIMIT_EXCEEDED = "QA_ARTIFACT_LIMIT_EXCEEDED"
PROVIDER_REAL_BLOCKED = "PROVIDER_REAL_BLOCKED"
PROVIDER_REAL_UNAVAILABLE = "PROVIDER_REAL_UNAVAILABLE"
PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
PROVIDER_CIRCUIT_OPEN = "PROVIDER_CIRCUIT_OPEN"
PROVIDER_COMPLETION_AMBIGUOUS = "PROVIDER_COMPLETION_AMBIGUOUS"
INTERNAL_AUTH_NOT_CONFIGURED = "INTERNAL_AUTH_NOT_CONFIGURED"
INTERNAL_AUTH_INVALID = "INTERNAL_AUTH_INVALID"
INTERNAL_AUTH_MISSING = "INTERNAL_AUTH_MISSING"
RELEASE_GATE_BLOCKED = "RELEASE_GATE_BLOCKED"
QA_RISK_CRITICAL = "QA_RISK_CRITICAL"
QA_FAILURE_DETECTED = "QA_FAILURE_DETECTED"
QA_ERROR_DETECTED = "QA_ERROR_DETECTED"
QA_WARNING_DETECTED = "QA_WARNING_DETECTED"
QA_LOCAL_HEURISTIC = "QA_LOCAL_HEURISTIC"

# Bloco 9 — Artifact Reader controlado por allowlist.
ARTIFACT_READER_DISABLED = "ARTIFACT_READER_DISABLED"
ARTIFACT_READER_USED = "ARTIFACT_READER_USED"
ARTIFACT_READER_PATH_NOT_ALLOWED = "ARTIFACT_READER_PATH_NOT_ALLOWED"
ARTIFACT_READER_EXTENSION_BLOCKED = "ARTIFACT_READER_EXTENSION_BLOCKED"
ARTIFACT_READER_FILE_TOO_LARGE = "ARTIFACT_READER_FILE_TOO_LARGE"
ARTIFACT_READER_TOTAL_LIMIT_EXCEEDED = "ARTIFACT_READER_TOTAL_LIMIT_EXCEEDED"
ARTIFACT_READER_ENV_BLOCKED = "ARTIFACT_READER_ENV_BLOCKED"
ARTIFACT_READER_BINARY_BLOCKED = "ARTIFACT_READER_BINARY_BLOCKED"
ARTIFACT_READER_PATH_TRAVERSAL_BLOCKED = "ARTIFACT_READER_PATH_TRAVERSAL_BLOCKED"
ARTIFACT_READER_SECRET_BLOCKED = "ARTIFACT_READER_SECRET_BLOCKED"

# Bloco 10 — QA visual stub (sem OCR, sem provider multimodal, sem Playwright).
VISUAL_QA_NOT_ENABLED = "VISUAL_QA_NOT_ENABLED"
VISUAL_QA_REQUIRES_HUMAN_REVIEW = "VISUAL_QA_REQUIRES_HUMAN_REVIEW"
VISUAL_QA_PROVIDER_NOT_CONFIGURED = "VISUAL_QA_PROVIDER_NOT_CONFIGURED"
VISUAL_QA_BLOCKED_FOR_RELEASE_GATE = "VISUAL_QA_BLOCKED_FOR_RELEASE_GATE"

# Bloco 11 — Agente exploratório assistido (plano/manual, sem execução).
EXPLORATION_ASSISTED_ONLY = "EXPLORATION_ASSISTED_ONLY"
EXPLORATION_ACTION_BLOCKED = "EXPLORATION_ACTION_BLOCKED"
HUMAN_CONFIRMATION_REQUIRED = "HUMAN_CONFIRMATION_REQUIRED"
EXPLORATION_CANNOT_EXECUTE_COMMANDS = "EXPLORATION_CANNOT_EXECUTE_COMMANDS"
EXPLORATION_CANNOT_ACCESS_SYSTEM = "EXPLORATION_CANNOT_ACCESS_SYSTEM"
EXPLORATION_RELEASE_GATE_BLOCKED = "EXPLORATION_RELEASE_GATE_BLOCKED"

# IMPLEMENT-05 — recursos reais controlados e enforcement final.
REAL_INTEGRATION_TESTS_DISABLED = "REAL_INTEGRATION_TESTS_DISABLED"
REAL_FINGUARD_TESTS_DISABLED = "REAL_FINGUARD_TESTS_DISABLED"
REAL_PROVIDER_TESTS_DISABLED = "REAL_PROVIDER_TESTS_DISABLED"
REAL_PLAYWRIGHT_TESTS_DISABLED = "REAL_PLAYWRIGHT_TESTS_DISABLED"
REAL_OCR_TESTS_DISABLED = "REAL_OCR_TESTS_DISABLED"
REAL_MULTIMODAL_TESTS_DISABLED = "REAL_MULTIMODAL_TESTS_DISABLED"
REAL_FEATURE_REQUIRES_EXPLICIT_FLAG = "REAL_FEATURE_REQUIRES_EXPLICIT_FLAG"
REAL_FEATURE_REQUIRES_HUMAN_CONFIRMATION = "REAL_FEATURE_REQUIRES_HUMAN_CONFIRMATION"
OCR_NOT_ENABLED = "OCR_NOT_ENABLED"
OCR_DEPENDENCY_UNAVAILABLE = "OCR_DEPENDENCY_UNAVAILABLE"
OCR_REQUIRES_HUMAN_REVIEW = "OCR_REQUIRES_HUMAN_REVIEW"
MULTIMODAL_PROVIDER_DISABLED = "MULTIMODAL_PROVIDER_DISABLED"
MULTIMODAL_PROVIDER_REQUIRES_EXPLICIT_AUTH = "MULTIMODAL_PROVIDER_REQUIRES_EXPLICIT_AUTH"
MULTIMODAL_PROVIDER_REQUIRES_FLAG = "MULTIMODAL_PROVIDER_REQUIRES_FLAG"
PLAYWRIGHT_NOT_ENABLED = "PLAYWRIGHT_NOT_ENABLED"
PLAYWRIGHT_DEPENDENCY_UNAVAILABLE = "PLAYWRIGHT_DEPENDENCY_UNAVAILABLE"
PLAYWRIGHT_BASE_URL_NOT_ALLOWED = "PLAYWRIGHT_BASE_URL_NOT_ALLOWED"
PLAYWRIGHT_READ_ONLY_MODE = "PLAYWRIGHT_READ_ONLY_MODE"
PLAYWRIGHT_ACTION_BLOCKED = "PLAYWRIGHT_ACTION_BLOCKED"
PLAYWRIGHT_REQUIRES_HUMAN_REVIEW = "PLAYWRIGHT_REQUIRES_HUMAN_REVIEW"
FINGUARD_REAL_INTEGRATION_DISABLED = "FINGUARD_REAL_INTEGRATION_DISABLED"
FINGUARD_REPOSITORY_ACCESS_BLOCKED = "FINGUARD_REPOSITORY_ACCESS_BLOCKED"
FINGUARD_TASK_NOT_ALLOWED = "FINGUARD_TASK_NOT_ALLOWED"
PROJECT_POLICY_ENFORCED = "PROJECT_POLICY_ENFORCED"
PROJECT_POLICY_BLOCKED = "PROJECT_POLICY_BLOCKED"
RELEASE_REQUIRES_HUMAN_REVIEW = "RELEASE_REQUIRES_HUMAN_REVIEW"
RELEASE_REAL_FEATURE_BLOCKED = "RELEASE_REAL_FEATURE_BLOCKED"

# ECOSYSTEM-INTELLIGENCE-SUITE-01 — assistente de ecossistema, memória técnica
# e provider local generativo opt-in.
FINANCIAL_DISCLAIMER = "FINANCIAL_DISCLAIMER"
REPORT_MEMORY_IS_NOT_TRAINING = "REPORT_MEMORY_IS_NOT_TRAINING"
REPORT_MEMORY_USED = "REPORT_MEMORY_USED"
REPORT_MEMORY_DISABLED = "REPORT_MEMORY_DISABLED"
REPORT_MEMORY_EMPTY = "REPORT_MEMORY_EMPTY"
REPORT_DUPLICATE_IGNORED = "REPORT_DUPLICATE_IGNORED"
REPORT_PERSISTENCE_UNAVAILABLE = "REPORT_PERSISTENCE_UNAVAILABLE"
INTERACTION_OUTCOME_DISABLED = "INTERACTION_OUTCOME_DISABLED"
INTERACTION_OUTCOME_DUPLICATE = "INTERACTION_OUTCOME_DUPLICATE"
INTERACTION_FEEDBACK_OBSERVATIONAL = "INTERACTION_FEEDBACK_OBSERVATIONAL"
INTERACTION_OUTCOME_PERSISTENCE_UNAVAILABLE = "INTERACTION_OUTCOME_PERSISTENCE_UNAVAILABLE"
OPERATIONAL_MEMORY_DISABLED = "OPERATIONAL_MEMORY_DISABLED"
LEARNING_CANDIDATE_DUPLICATE = "LEARNING_CANDIDATE_DUPLICATE"
OPERATIONAL_EVIDENCE_NOT_FOUND = "OPERATIONAL_EVIDENCE_NOT_FOUND"
OPERATIONAL_SINGLE_EVIDENCE_NOT_PROMOTED = "OPERATIONAL_SINGLE_EVIDENCE_NOT_PROMOTED"
OPERATIONAL_CONTRADICTION_PRESERVED = "OPERATIONAL_CONTRADICTION_PRESERVED"
OPERATIONAL_PATTERN_RESOLVED = "OPERATIONAL_PATTERN_RESOLVED"
OPERATIONAL_MEMORY_PERSISTENCE_UNAVAILABLE = "OPERATIONAL_MEMORY_PERSISTENCE_UNAVAILABLE"
RISK_CONTRACT_CONFIGURATION_INVALID = "RISK_CONTRACT_CONFIGURATION_INVALID"
RISK_OVERRIDE_NOT_AUTHORIZED = "RISK_OVERRIDE_NOT_AUTHORIZED"
EXECUTION_EVIDENCE_SCOPE_MISMATCH = "EXECUTION_EVIDENCE_SCOPE_MISMATCH"
LOCAL_MODEL_DISABLED = "LOCAL_MODEL_DISABLED"
LOCAL_MODEL_NOT_AUTHORIZED = "LOCAL_MODEL_NOT_AUTHORIZED"
LOCAL_MODEL_TASK_BLOCKED = "LOCAL_MODEL_TASK_BLOCKED"
LOCAL_MODEL_TRANSPORT_UNAVAILABLE = "LOCAL_MODEL_TRANSPORT_UNAVAILABLE"
LOCAL_MODEL_USED = "LOCAL_MODEL_USED"
TRAINING_CANDIDATE_ADMIN_REQUIRED = "TRAINING_CANDIDATE_ADMIN_REQUIRED"
TRAINING_CANDIDATE_PERSISTENCE_UNAVAILABLE = "TRAINING_CANDIDATE_PERSISTENCE_UNAVAILABLE"
TRAINING_CANDIDATE_SOURCE_NOT_FOUND = "TRAINING_CANDIDATE_SOURCE_NOT_FOUND"
TRAINING_CANDIDATE_TRANSITION_REJECTED = "TRAINING_CANDIDATE_TRANSITION_REJECTED"

# MULTI-PROVIDER-SAFE-EVOLUTION Etapa 2 — identidade autenticada do caller e
# autorização de provider por projeto/ambiente (fail-closed).
CALLER_CREDENTIAL_MISSING = "CALLER_CREDENTIAL_MISSING"
CALLER_CREDENTIAL_UNKNOWN = "CALLER_CREDENTIAL_UNKNOWN"
CALLER_REGISTRY_INVALID = "CALLER_REGISTRY_INVALID"
CALLER_ORIGIN_MISMATCH = "CALLER_ORIGIN_MISMATCH"
CALLER_PROVIDER_SELECTION_NOT_ALLOWED = "CALLER_PROVIDER_SELECTION_NOT_ALLOWED"
CALLER_MODEL_SELECTION_NOT_ALLOWED = "CALLER_MODEL_SELECTION_NOT_ALLOWED"
CALLER_REPORT_ACCESS_NOT_ALLOWED = "CALLER_REPORT_ACCESS_NOT_ALLOWED"
CALLER_REPORT_PRODUCER_MISMATCH = "CALLER_REPORT_PRODUCER_MISMATCH"
CALLER_IDENTITY_SHARED_CREDENTIAL = "CALLER_IDENTITY_SHARED_CREDENTIAL"
CALLER_IDENTITY_AMBIGUOUS = "CALLER_IDENTITY_AMBIGUOUS"
PROVIDER_NOT_AUTHORIZED_FOR_PROJECT = "PROVIDER_NOT_AUTHORIZED_FOR_PROJECT"
PROVIDER_NOT_HOMOLOGATED = "PROVIDER_NOT_HOMOLOGATED"
PROVIDER_NOT_IMPLEMENTED = "PROVIDER_NOT_IMPLEMENTED"

# MULTI-PROVIDER-SAFE-EVOLUTION Etapa 3 — provider e modelo validados como
# unidade. Combinação inválida é bloqueada ANTES de qualquer adapter.
MODEL_UNKNOWN = "MODEL_UNKNOWN"
MODEL_PROVIDER_MISMATCH = "MODEL_PROVIDER_MISMATCH"
MODEL_NOT_AUTHORIZED = "MODEL_NOT_AUTHORIZED"
MODEL_TASK_INCOMPATIBLE = "MODEL_TASK_INCOMPATIBLE"
MODEL_NOT_ALLOWED_FOR_CALLER = "MODEL_NOT_ALLOWED_FOR_CALLER"
MODEL_NOT_ALLOWED_IN_AUTO = "MODEL_NOT_ALLOWED_IN_AUTO"
MODEL_DEFAULT_UNAVAILABLE = "MODEL_DEFAULT_UNAVAILABLE"
PROVIDER_MODEL_BINDING_INVALID = "PROVIDER_MODEL_BINDING_INVALID"

# PROVIDER-OUTPUT-BUDGET-CANCELLATION-01 — orçamento de saída, timeout de
# transporte e término de geração.
PROVIDER_OUTPUT_TRUNCATED = "PROVIDER_OUTPUT_TRUNCATED"
PROVIDER_OUTPUT_REJECTED = "PROVIDER_OUTPUT_REJECTED"
PROVIDER_TRANSPORT_TIMEOUT = "PROVIDER_TRANSPORT_TIMEOUT"

# ELYRA ONBOARDING V1 TEXTUAL — contrato tipado e fail-closed.
ELYRA_INPUT_SCHEMA_INVALID = "ELYRA_INPUT_SCHEMA_INVALID"
ELYRA_CALLER_NOT_REGISTERED = "ELYRA_CALLER_NOT_REGISTERED"
ELYRA_CONSENT_REQUIRED = "ELYRA_CONSENT_REQUIRED"
ELYRA_PROVIDER_POLICY_DENIED = "ELYRA_PROVIDER_POLICY_DENIED"
ELYRA_PROVIDER_MISMATCH = "ELYRA_PROVIDER_MISMATCH"
ELYRA_OUTPUT_INVALID = "ELYRA_OUTPUT_INVALID"
ELYRA_IDEMPOTENCY_CONFLICT = "ELYRA_IDEMPOTENCY_CONFLICT"
ELYRA_INTERNAL_FAILURE = "ELYRA_INTERNAL_FAILURE"

# ELYRA MULTIMODAL V1 (Stage 12) — capability propria, separada da textual.
ELYRA_MULTIMODAL_INPUT_SCHEMA_INVALID = "ELYRA_MULTIMODAL_INPUT_SCHEMA_INVALID"
ELYRA_MULTIMODAL_CALLER_NOT_REGISTERED = "ELYRA_MULTIMODAL_CALLER_NOT_REGISTERED"
ELYRA_MULTIMODAL_CONSENT_REQUIRED = "ELYRA_MULTIMODAL_CONSENT_REQUIRED"
ELYRA_MULTIMODAL_PROVIDER_POLICY_DENIED = "ELYRA_MULTIMODAL_PROVIDER_POLICY_DENIED"
ELYRA_MULTIMODAL_PROVIDER_MISMATCH = "ELYRA_MULTIMODAL_PROVIDER_MISMATCH"
ELYRA_MULTIMODAL_OUTPUT_INVALID = "ELYRA_MULTIMODAL_OUTPUT_INVALID"
ELYRA_MULTIMODAL_IDEMPOTENCY_CONFLICT = "ELYRA_MULTIMODAL_IDEMPOTENCY_CONFLICT"
ELYRA_MULTIMODAL_INTERNAL_FAILURE = "ELYRA_MULTIMODAL_INTERNAL_FAILURE"

# ELYRA LEARNING GOVERNADO V1 (Stage 13) — capability estreita: submeter e revogar.
ELYRA_LEARNING_INPUT_SCHEMA_INVALID = "ELYRA_LEARNING_INPUT_SCHEMA_INVALID"
ELYRA_LEARNING_CALLER_NOT_REGISTERED = "ELYRA_LEARNING_CALLER_NOT_REGISTERED"
ELYRA_LEARNING_TRAINING_CONSENT_REQUIRED = "ELYRA_LEARNING_TRAINING_CONSENT_REQUIRED"
ELYRA_LEARNING_NOT_ELIGIBLE = "ELYRA_LEARNING_NOT_ELIGIBLE"
ELYRA_LEARNING_PROVENANCE_REQUIRED = "ELYRA_LEARNING_PROVENANCE_REQUIRED"
ELYRA_LEARNING_FINGERPRINT_MISMATCH = "ELYRA_LEARNING_FINGERPRINT_MISMATCH"
ELYRA_LEARNING_QUALITY_GATE_FAILED = "ELYRA_LEARNING_QUALITY_GATE_FAILED"
ELYRA_LEARNING_OPERATION_NOT_SUPPORTED = "ELYRA_LEARNING_OPERATION_NOT_SUPPORTED"
ELYRA_LEARNING_CANDIDATE_NOT_FOUND = "ELYRA_LEARNING_CANDIDATE_NOT_FOUND"
ELYRA_LEARNING_INTERNAL_FAILURE = "ELYRA_LEARNING_INTERNAL_FAILURE"

_SEVERITIES: dict[str, str] = {
    QA_NO_ARTIFACTS: SEVERITY_WARNING,
    QA_FALLBACK_MOCK: SEVERITY_WARNING,
    PROJECT_TASK_NOT_ALLOWED: SEVERITY_WARNING,
    PROJECT_POLICY_NOT_ENFORCED: SEVERITY_INFO,
    UNKNOWN_ORIGIN_SYSTEM: SEVERITY_WARNING,
    UNKNOWN_TASK_TYPE: SEVERITY_WARNING,
    ARTIFACT_VISUAL_UNSUPPORTED: SEVERITY_WARNING,
    ARTIFACT_TRUNCATED: SEVERITY_WARNING,
    ARTIFACT_PATH_REJECTED: SEVERITY_ERROR,
    ARTIFACT_EMPTY_CONTENT: SEVERITY_WARNING,
    ARTIFACT_TYPE_UNKNOWN: SEVERITY_WARNING,
    QA_ARTIFACT_LIMIT_EXCEEDED: SEVERITY_WARNING,
    PROVIDER_REAL_BLOCKED: SEVERITY_WARNING,
    PROVIDER_REAL_UNAVAILABLE: SEVERITY_WARNING,
    PROVIDER_TIMEOUT: SEVERITY_WARNING,
    PROVIDER_CIRCUIT_OPEN: SEVERITY_WARNING,
    PROVIDER_COMPLETION_AMBIGUOUS: SEVERITY_WARNING,
    INTERNAL_AUTH_NOT_CONFIGURED: SEVERITY_WARNING,
    INTERNAL_AUTH_INVALID: SEVERITY_ERROR,
    INTERNAL_AUTH_MISSING: SEVERITY_ERROR,
    RELEASE_GATE_BLOCKED: SEVERITY_ERROR,
    QA_RISK_CRITICAL: SEVERITY_CRITICAL,
    QA_FAILURE_DETECTED: SEVERITY_ERROR,
    QA_ERROR_DETECTED: SEVERITY_ERROR,
    QA_WARNING_DETECTED: SEVERITY_WARNING,
    QA_LOCAL_HEURISTIC: SEVERITY_INFO,
    ARTIFACT_READER_DISABLED: SEVERITY_WARNING,
    ARTIFACT_READER_USED: SEVERITY_INFO,
    ARTIFACT_READER_PATH_NOT_ALLOWED: SEVERITY_ERROR,
    ARTIFACT_READER_EXTENSION_BLOCKED: SEVERITY_ERROR,
    ARTIFACT_READER_FILE_TOO_LARGE: SEVERITY_WARNING,
    ARTIFACT_READER_TOTAL_LIMIT_EXCEEDED: SEVERITY_WARNING,
    ARTIFACT_READER_ENV_BLOCKED: SEVERITY_CRITICAL,
    ARTIFACT_READER_BINARY_BLOCKED: SEVERITY_ERROR,
    ARTIFACT_READER_PATH_TRAVERSAL_BLOCKED: SEVERITY_ERROR,
    ARTIFACT_READER_SECRET_BLOCKED: SEVERITY_CRITICAL,
    VISUAL_QA_NOT_ENABLED: SEVERITY_WARNING,
    VISUAL_QA_REQUIRES_HUMAN_REVIEW: SEVERITY_WARNING,
    VISUAL_QA_PROVIDER_NOT_CONFIGURED: SEVERITY_INFO,
    VISUAL_QA_BLOCKED_FOR_RELEASE_GATE: SEVERITY_ERROR,
    EXPLORATION_ASSISTED_ONLY: SEVERITY_INFO,
    EXPLORATION_ACTION_BLOCKED: SEVERITY_WARNING,
    HUMAN_CONFIRMATION_REQUIRED: SEVERITY_WARNING,
    EXPLORATION_CANNOT_EXECUTE_COMMANDS: SEVERITY_INFO,
    EXPLORATION_CANNOT_ACCESS_SYSTEM: SEVERITY_INFO,
    EXPLORATION_RELEASE_GATE_BLOCKED: SEVERITY_ERROR,
    REAL_INTEGRATION_TESTS_DISABLED: SEVERITY_INFO,
    REAL_FINGUARD_TESTS_DISABLED: SEVERITY_INFO,
    REAL_PROVIDER_TESTS_DISABLED: SEVERITY_INFO,
    REAL_PLAYWRIGHT_TESTS_DISABLED: SEVERITY_INFO,
    REAL_OCR_TESTS_DISABLED: SEVERITY_INFO,
    REAL_MULTIMODAL_TESTS_DISABLED: SEVERITY_INFO,
    REAL_FEATURE_REQUIRES_EXPLICIT_FLAG: SEVERITY_WARNING,
    REAL_FEATURE_REQUIRES_HUMAN_CONFIRMATION: SEVERITY_WARNING,
    OCR_NOT_ENABLED: SEVERITY_WARNING,
    OCR_DEPENDENCY_UNAVAILABLE: SEVERITY_WARNING,
    OCR_REQUIRES_HUMAN_REVIEW: SEVERITY_WARNING,
    MULTIMODAL_PROVIDER_DISABLED: SEVERITY_WARNING,
    MULTIMODAL_PROVIDER_REQUIRES_EXPLICIT_AUTH: SEVERITY_WARNING,
    MULTIMODAL_PROVIDER_REQUIRES_FLAG: SEVERITY_WARNING,
    PLAYWRIGHT_NOT_ENABLED: SEVERITY_WARNING,
    PLAYWRIGHT_DEPENDENCY_UNAVAILABLE: SEVERITY_WARNING,
    PLAYWRIGHT_BASE_URL_NOT_ALLOWED: SEVERITY_ERROR,
    PLAYWRIGHT_READ_ONLY_MODE: SEVERITY_INFO,
    PLAYWRIGHT_ACTION_BLOCKED: SEVERITY_ERROR,
    PLAYWRIGHT_REQUIRES_HUMAN_REVIEW: SEVERITY_WARNING,
    FINGUARD_REAL_INTEGRATION_DISABLED: SEVERITY_INFO,
    FINGUARD_REPOSITORY_ACCESS_BLOCKED: SEVERITY_ERROR,
    FINGUARD_TASK_NOT_ALLOWED: SEVERITY_ERROR,
    PROJECT_POLICY_ENFORCED: SEVERITY_INFO,
    PROJECT_POLICY_BLOCKED: SEVERITY_ERROR,
    RELEASE_REQUIRES_HUMAN_REVIEW: SEVERITY_ERROR,
    RELEASE_REAL_FEATURE_BLOCKED: SEVERITY_ERROR,
    FINANCIAL_DISCLAIMER: SEVERITY_INFO,
    REPORT_MEMORY_IS_NOT_TRAINING: SEVERITY_INFO,
    REPORT_MEMORY_USED: SEVERITY_INFO,
    REPORT_MEMORY_DISABLED: SEVERITY_WARNING,
    REPORT_MEMORY_EMPTY: SEVERITY_INFO,
    REPORT_DUPLICATE_IGNORED: SEVERITY_INFO,
    REPORT_PERSISTENCE_UNAVAILABLE: SEVERITY_ERROR,
    INTERACTION_OUTCOME_DISABLED: SEVERITY_WARNING,
    INTERACTION_OUTCOME_DUPLICATE: SEVERITY_INFO,
    INTERACTION_FEEDBACK_OBSERVATIONAL: SEVERITY_INFO,
    INTERACTION_OUTCOME_PERSISTENCE_UNAVAILABLE: SEVERITY_ERROR,
    OPERATIONAL_MEMORY_DISABLED: SEVERITY_WARNING,
    LEARNING_CANDIDATE_DUPLICATE: SEVERITY_INFO,
    OPERATIONAL_EVIDENCE_NOT_FOUND: SEVERITY_ERROR,
    OPERATIONAL_SINGLE_EVIDENCE_NOT_PROMOTED: SEVERITY_INFO,
    OPERATIONAL_CONTRADICTION_PRESERVED: SEVERITY_WARNING,
    OPERATIONAL_PATTERN_RESOLVED: SEVERITY_INFO,
    OPERATIONAL_MEMORY_PERSISTENCE_UNAVAILABLE: SEVERITY_ERROR,
    RISK_CONTRACT_CONFIGURATION_INVALID: SEVERITY_CRITICAL,
    RISK_OVERRIDE_NOT_AUTHORIZED: SEVERITY_ERROR,
    EXECUTION_EVIDENCE_SCOPE_MISMATCH: SEVERITY_ERROR,
    LOCAL_MODEL_DISABLED: SEVERITY_WARNING,
    LOCAL_MODEL_NOT_AUTHORIZED: SEVERITY_WARNING,
    LOCAL_MODEL_TASK_BLOCKED: SEVERITY_ERROR,
    LOCAL_MODEL_TRANSPORT_UNAVAILABLE: SEVERITY_WARNING,
    LOCAL_MODEL_USED: SEVERITY_INFO,
    TRAINING_CANDIDATE_ADMIN_REQUIRED: SEVERITY_ERROR,
    TRAINING_CANDIDATE_PERSISTENCE_UNAVAILABLE: SEVERITY_ERROR,
    TRAINING_CANDIDATE_SOURCE_NOT_FOUND: SEVERITY_ERROR,
    TRAINING_CANDIDATE_TRANSITION_REJECTED: SEVERITY_ERROR,
    CALLER_CREDENTIAL_MISSING: SEVERITY_ERROR,
    CALLER_CREDENTIAL_UNKNOWN: SEVERITY_ERROR,
    CALLER_REGISTRY_INVALID: SEVERITY_CRITICAL,
    CALLER_ORIGIN_MISMATCH: SEVERITY_ERROR,
    CALLER_PROVIDER_SELECTION_NOT_ALLOWED: SEVERITY_ERROR,
    CALLER_MODEL_SELECTION_NOT_ALLOWED: SEVERITY_ERROR,
    CALLER_REPORT_ACCESS_NOT_ALLOWED: SEVERITY_ERROR,
    CALLER_REPORT_PRODUCER_MISMATCH: SEVERITY_ERROR,
    CALLER_IDENTITY_SHARED_CREDENTIAL: SEVERITY_INFO,
    CALLER_IDENTITY_AMBIGUOUS: SEVERITY_ERROR,
    PROVIDER_NOT_AUTHORIZED_FOR_PROJECT: SEVERITY_ERROR,
    PROVIDER_NOT_HOMOLOGATED: SEVERITY_WARNING,
    PROVIDER_NOT_IMPLEMENTED: SEVERITY_WARNING,
    MODEL_UNKNOWN: SEVERITY_ERROR,
    MODEL_PROVIDER_MISMATCH: SEVERITY_ERROR,
    MODEL_NOT_AUTHORIZED: SEVERITY_ERROR,
    MODEL_TASK_INCOMPATIBLE: SEVERITY_ERROR,
    MODEL_NOT_ALLOWED_FOR_CALLER: SEVERITY_ERROR,
    MODEL_NOT_ALLOWED_IN_AUTO: SEVERITY_ERROR,
    MODEL_DEFAULT_UNAVAILABLE: SEVERITY_WARNING,
    PROVIDER_MODEL_BINDING_INVALID: SEVERITY_ERROR,
    PROVIDER_OUTPUT_TRUNCATED: SEVERITY_WARNING,
    PROVIDER_OUTPUT_REJECTED: SEVERITY_WARNING,
    PROVIDER_TRANSPORT_TIMEOUT: SEVERITY_WARNING,
    ELYRA_INPUT_SCHEMA_INVALID: SEVERITY_ERROR,
    ELYRA_CALLER_NOT_REGISTERED: SEVERITY_ERROR,
    ELYRA_CONSENT_REQUIRED: SEVERITY_ERROR,
    ELYRA_PROVIDER_POLICY_DENIED: SEVERITY_ERROR,
    ELYRA_PROVIDER_MISMATCH: SEVERITY_ERROR,
    ELYRA_OUTPUT_INVALID: SEVERITY_ERROR,
    ELYRA_IDEMPOTENCY_CONFLICT: SEVERITY_ERROR,
    ELYRA_INTERNAL_FAILURE: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_INPUT_SCHEMA_INVALID: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_CALLER_NOT_REGISTERED: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_CONSENT_REQUIRED: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_PROVIDER_POLICY_DENIED: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_PROVIDER_MISMATCH: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_OUTPUT_INVALID: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_IDEMPOTENCY_CONFLICT: SEVERITY_ERROR,
    ELYRA_MULTIMODAL_INTERNAL_FAILURE: SEVERITY_ERROR,
    ELYRA_LEARNING_INPUT_SCHEMA_INVALID: SEVERITY_ERROR,
    ELYRA_LEARNING_CALLER_NOT_REGISTERED: SEVERITY_ERROR,
    ELYRA_LEARNING_TRAINING_CONSENT_REQUIRED: SEVERITY_ERROR,
    ELYRA_LEARNING_NOT_ELIGIBLE: SEVERITY_ERROR,
    ELYRA_LEARNING_PROVENANCE_REQUIRED: SEVERITY_ERROR,
    ELYRA_LEARNING_FINGERPRINT_MISMATCH: SEVERITY_ERROR,
    ELYRA_LEARNING_QUALITY_GATE_FAILED: SEVERITY_ERROR,
    ELYRA_LEARNING_OPERATION_NOT_SUPPORTED: SEVERITY_ERROR,
    ELYRA_LEARNING_CANDIDATE_NOT_FOUND: SEVERITY_ERROR,
    ELYRA_LEARNING_INTERNAL_FAILURE: SEVERITY_ERROR,
}


class WarningItem(BaseModel):
    code: str
    message: str
    severity: str = SEVERITY_WARNING


def severity_for(code: str) -> str:
    return _SEVERITIES.get(code, SEVERITY_WARNING)


def make_warning(code: str, message: str, severity: str | None = None) -> WarningItem:
    return WarningItem(code=code, message=message, severity=severity or severity_for(code))
